version: "3"

services:
  src:
    build: 
      context: .
      dockerfile: ./deploy/docker/Dockerfile
    ports:
      - "22367:22367"
    volumes:
      - '.:/app'
      - '/etc/localtime:/etc/localtime:ro'